# Baixa a imagem do ubuntu
FROM ubuntu
LABEL maintainer="Higor Martins <higgor.m@gmail.com>"

#Remover a versão atual do PHP
RUN apt-get remove --purge php5* 

#Adicionar o repositório do PHP5.6 e atualizar a listagem de pacotes
RUN add-apt-repository ppa:ondrej/php
RUN apt-get update

# Instalação dos pacotes
RUN apt-get update && apt-get install -y \
apache2 \
php5.6 \
php5.6-cli \
php5.6-common \
php5.6-gd \
php5.6-json \
php5.6-ldap \
php5.6-mysql \
php5.6-pgsql \
php5.6-apcu \
php5.6-imagick \
php5.6-mcrypt \
php5.6-sybase \
php5.6-xdebug \
libapache2-mod-php5.6
curl \
phpunit \
nano \
&& apt-get clean && apt-get autoclean && apt-get autoremove \
&& rm -rf /var/lib/apt/lists/*

# Habilita o modo de reescrita do apache
RUN a2enmod rewrite

ENV APACHE_LOCK_DIR="/var/lock"
ENV APACHE_PID_FILE="/var/run/apache2.pid"
ENV APACHE_RUN_USER="www-data"
ENV APACHE_RUN_GROUP="www-data"
ENV APACHE_LOG_DIR="/var/log/apache2"

LABEL Description="Webserver php 5.6.38"

VOLUME /var/www/html

ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Copia o arquivo de virtualhost
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

# Install composer
WORKDIR /usr/local/bin/
RUN curl -sS https://getcomposer.org/installer | php
RUN chmod +x composer.phar
RUN mv composer.phar composer
RUN composer self-update

# Set path bin
WORKDIR /root
RUN echo 'export PATH="$PATH:$HOME/.composer/vendor/bin"' >> ~/.bashrc

WORKDIR /var/www/html

COPY apache2-foreground.sh /scripts/
RUN chmod +x /scripts/*

EXPOSE 80

CMD ["/scripts/apache2-foreground.sh"]
